name: deploy-trade-prod
on:
  release:
    types: [published]
  workflow_dispatch:
concurrency: deploy-trade-prod

jobs:
  deploy-trade-prod:
    runs-on: ubuntu-20.04
    environment: trade

    steps:
      - name: deploy application
        run: echo "DEPLOY $GITHUB_REF $GITHUB_SHA" && sleep 30
