name: deploy-production
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-fenix:
    runs-on: ubuntu-20.04
    environment: fenix

    steps:
      - name: deploy application
        run: echo "DEPLOYED $GITHUB_REF"
        
  deploy-trade:
    runs-on: ubuntu-20.04
    environment: trade

    steps:
      - name: deploy application
        run: echo "DEPLOYED $GITHUB_REF"
