name: deploy-production
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-20.04
    environment: production

    steps:
      - name: deploy application
        run: echo "DEPLOYED $GITHUB_REF"
