name: deploy-fenix-prod
on:
  release:
    types: [published]
  workflow_dispatch:
concurrency: deploy-fenix-prod

jobs:
  deploy-fenix-prod:
    runs-on: ubuntu-20.04
    environment: fenix

    steps:
      - name: deploy application
        run: echo "DEPLOY $GITHUB_REF $GITHUB_SHA"
