name: deploy-fenix-prod
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-fenix-prod:
    runs-on: ubuntu-20.04
    environment: fenix

    steps:
      - name: deploy application
        run: echo "DEPLOYED $GITHUB_REF"
