name: Revision number increment

on:
  push:
    branches:
      - main
    tags-ignore:
      - r*

jobs:
  revision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: bash .github/tag.sh
